export { default as Header } from './Header'
export { default as Avatar } from './Avatar'
export { default as RecentSlides } from './HomeComponents/RecentSlides'
export { default as Slide } from './HomeComponents/Slide'
export { default as Feed } from './HomeComponents/Feed'
export { default as SearchBar } from './SearchComponents/SearchBar'
export { default as SearchFeed } from './SearchComponents/SearchFeed'
export { default as MovieCard } from './MovieCard'
export { default as MoviePlayer } from './PlayerComponents/MoviePlayer'
export { default as VideoDetails } from './PlayerComponents/VideoDetails'
export { default as PhoneInput } from './LoginComponents/PhoneInput'
export { default as OtpInput } from './LoginComponents/OtpInput'
export { default as EditModal } from './ProfileComponents/EditModal'
export { default as VideosList } from './ProfileComponents/VideosList'
export { default as CachedImage } from './CachedImage'
export {default as Icon} from "./Icon"